# Generated by Django 5.1.5 on 2025-01-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarDiary', '0006_calendardiary_add_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendardiary',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
